name: Tests

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: license_core_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          extensions: pdo, pdo_mysql, mysql

      - name: Get composer cache dir
        id: composer-cache-dir
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Validate composer files
        run: composer validate --strict

      - name: Install Dependencies
        run: |
          if ! composer install -q --no-interaction --prefer-dist; then
            echo "composer install failed, trying composer update..."
            composer update -q --no-interaction --prefer-dist
          fi

      - name: Prep Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 -u root --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run static analysis check
        run:  ./vendor/bin/phpstan analyse --memory-limit=2G -c phpstan.neon

      - name: Run Tests
        env:
          DB_DATABASE: license_core_test
          DB_CONNECTION: mysql_testing
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: root
          DB_PASSWORD: ''
          LICENSE_AES_SECRET: "license_aes_secret"
          LICENSE_AES_IV: "cf5879a288df134f"
          BRAND_AES_SECRET: "brand_aes_secret"
          BRAND_AES_IV: "cf4279a288df134f"

        run: ./vendor/bin/pest --parallel

      - name: Code style fixes
        run: ./vendor/bin/pint

